#!/bin/bash
ip=$(ifconfig | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' |head -n1)
mkcert -install
mkcert -cert-file cert.pem -key-file key.pem 0.0.0.0 localhost 127.0.0.1 $ip
python manage.py runsslserver --certificate cert.pem --key key.pem 0.0.0.0:8000
