# Generated by Django 4.1 on 2022-10-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('listener_name', models.CharField(max_length=100)),
                ('ip', models.IntegerField()),
            ],
        ),
    ]
