# Generated by Django 4.1 on 2022-10-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListenerForm',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='PayloadForm',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='listener_name',
        ),
    ]
