# Generated by Django 4.1 on 2022-10-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenerform',
            name='stoped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
