# Generated by Django 4.1.2 on 2022-12-13 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
