# Generated by Django 3.2.13 on 2022-12-15 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_listenerform_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
