# Generated by Django 4.1.2 on 2023-02-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_agent_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.agent')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.modules')),
            ],
        ),
    ]
