# Generated by Django 4.1.2 on 2023-05-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_agenttasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
